apiVersion: v1
kind: Namespace
metadata:
  name: cruiseapp
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv-volume
  namespace: cruiseapp
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pv-claim
  namespace: cruiseapp
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: cruiseapp
spec:
  selector:
    matchLabels:
      app: database
  serviceName: database-service
  replicas: 3
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database 
        image: syllanfadocker/group-997959_database
        env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
        ports:
        - containerPort: 3306
          name: database
      volumes:
        - name : database-pv-volume
          persistentVolumeClaim:
            claimName: database-pv-claim

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: cruiseapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: syllanfadocker/group-997959_api
          env:
            - name: DB_HOST
              value: DB_IP
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: "password"
          ports:
            - containerPort: 8000
          volumes:
          - name : database-pv-volume
            persistentVolumeClaim:
              claimName: database-pv-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: cruiseapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: syllanfadocker/group-997959_front
          ports:
            - containerPort: 4200
          volumes:
          - name : database-pv-volume
            persistentVolumeClaim:
              claimName: database-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: cruiseapp
spec:
  selector:
    app: database
  ports:
    - name: database-port
      port: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: cruiseapp
spec:
  selector:
    app: api
  ports:
    - name: api-port
      port: 8000
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: cruiseapp
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
  type: LoadBalancer
